name: Terraform Deploy 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
#When using aws-actions/configure-aws-credentials with OIDC, you must give 
#the job permission to request an OIDC ID token from GitHub

    permissions: #OIDC IAM Related
      id-token: write   # required for requesting OIDC token
      contents: read    # required for actions/checkout

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials from role
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::180294178330:role/github_trust_role
          role-session-name: github-actions
          aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.0

    - name: Terraform Format
      run: terraform fmt -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate 

    - name: Terraform Plan
      run: terraform plan -out=tfplan


    - name: Terraform Apply (extra debug info)
      if: github.ref == 'refs/heads/main'
      run: |
        terraform apply -auto-approve
        

